### ISSUE TITLE
Return an array from get_mc_number_photon_electron

### ISSUE THREAD

**Issue by watsonjj** [cta-observatory/pyhessio#18]
Can get_mc_number_photon_electron be changed to return a np array of the pe_count for the entire camera, removing the pixel_id argument?

Currently it does return an array, however this is an array of just the pixel_id requested. 

I attempted to make the changes myself, but I'm not sure how to test those changes without them being integrated into the github first.

**Comment by watsonjj** [comment]
I have implemented this now. I have also fixed a bug where telescope_id was used instead of itel. I will submit a pull request later.

To test this, i uninstalled pyhessio from conda, and then instead used pip to install it, and put sys.path.append('/Users/Jason/Software/pyhessio/') into my ctapipe code. Then I would uninstall and reinstall pyhessio when I made changes. Is there a better way to test changes to pyhessio?

**Comment by jacquemier** [comment]
You do not need to uninstall pyhessio from conda and reinstall it.
Just need to  execute:
 
$ python setup.py develop
$ py.test

**Comment by jacquemier** [comment]
In with function did you fixe a bug where telescope_id was used instead of itel ?

**Comment by watsonjj** [comment]
in pyhessio.c, get_mc_number_photon_electron:

	 *pe = hsdata->mc_event.mc_pe_list[telescope_id].pe_count[pixel_id];
should have been
	 *pe = hsdata->mc_event.mc_pe_list[itel].pe_count[pixel_id];
Thanks for the help!

**Comment by jacquemier** [comment]
Jason, 

Thank you for participating in pyhessio development, 

Do not hesitate if you have other questions, 

Regards, Jean 

| De: "Jason Watson" <notifications@github.com>
| À: "cta-observatory/pyhessio" <pyhessio@noreply.github.com>
| Cc: "Jean Jacquemier" <jacquem@lapp.in2p3.fr>
| Envoyé: Mercredi 23 Mars 2016 09:42:14
| Objet: Re: [pyhessio] Return an array from get_mc_number_photon_electron (#18)

| in pyhessio.c, get_mc_number_photon_electron:
| *pe = hsdata->mc_event.mc_pe_list[telescope_id].pe_count[pixel_id];

| should have been
| *pe = hsdata->mc_event.mc_pe_list[itel].pe_count[pixel_id];
| Thanks for the help!

| —
| You are receiving this because you commented.
| Reply to this email directly or view it on GitHub

**Comment by jacquemier** [comment]
Dear Jason, 

If I do not any mistake, you did not submit pull request for issue below. 
Do you plan to submit it ? 
Regards, Jean 

| De: "Jason Watson" <notifications@github.com>
| À: "cta-observatory/pyhessio" <pyhessio@noreply.github.com>
| Envoyé: Mercredi 23 Mars 2016 09:17:36
| Objet: Re: [pyhessio] Return an array from get_mc_number_photon_electron (#18)

| I have implemented this now. I have also fixed a bug where telescope_id was used
| instead of itel. I will submit a pull request later.

| To test this, i uninstalled pyhessio from conda, and then instead used pip to
| install it, and put sys.path.append('/Users/Jason/Software/pyhessio/') into my
| ctapipe code. Then I would uninstall and reinstall pyhessio when I made
| changes. Is there a better way to test changes to pyhessio?

| —
| You are receiving this because you are subscribed to this thread.
| Reply to this email directly or view it on GitHub

**Comment by tino-michael** [comment]
Hi, to jump into this discussion: As far as I can see, _pyhessio.get_mc_number_photon_electron(tel_id, pix_id)_ now returns only an array with a single 0 in it. The entry is always zero...
Is this interface still under construction and not usable yet?

**Comment by watsonjj** [comment]
Hi Jean, yes I will submit it next week.

Tino - Apparently only certain sim_telarray files have this information stored, but I'm not sure about that. The files I have do have it stored.
