### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by cbigo68** [cta-observatory/pyhessio#54]
Hi, 

we followed this few steps:
```
conda create -n cta python=3.5
source activate cta
git clone https://github.com/cta-observatory/pyhessio
cd pyhessio
python setup.py install
```

but get this:
```
/home/bigongiari/Software/miniconda3/envs/pyhessio/compiler_compat/ld: cannot find -lpthread
/home/bigongiari/Software/miniconda3/envs/pyhessio/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

Read somewhere I could add a line to `setup.py`:
```
extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']
```
Could this fix the problem?
Where exactly should I put that line in `setup.py`?

Thx

**Comment by kosack** [comment]
Can you just install it via `conda install pyhessio`?  It seems like you are just missing the developer libraries on your machine, needed for compilation. You should not need to modify setup.py

**Comment by kosack** [comment]
Also, we now recommend using python 3.6 - support for 3.5 may go away at some point.

If you are installing pyhessio to read MC data, you might  want to look at ctapipe instead  (ctapipe uses pyhessio internally), since it provides a higher-level user interface on top that works with simulations and other data. Pyhessio is only intended as a low-level library.

**Comment by cbigo68** [comment]
Worked.
Could you update the `README.md`? 
It still has the procedure I followed at the beginning..

**Comment by kosack** [comment]
Done.  The old procedure was for building from source, so it's been noted in the readme.
